Add Bytes to_buffer and to_alloc_vec
stellar/rs-soroban-sdk pull request #1231
Opened 2024-02-14 14:37 UTC by leighmcculloch

### What
Add Bytes to_buffer and to_alloc_vec functions that provide access to the bytes in local guest memory. The to_buffer function provides access to the bytes in a statically specified buffer. The to_alloc_vec function is available only when the alloc feature is enabled and provides access to an alloc::vec::Vec containing the bytes.

### Why
@tomerweller was talking to me about allocator usage in dev and testing when experimenting and costs are not that high, and it got me thinking that I mostly don't use the allocator because it's not trivial to get data into an allocated type. It's not that hard, but I don't think it's obvious and it's something we need to explain to people how to do.

These functions provide two ways to get access to the data inside a variable length Bytes value, whether using the allocator or not.

The first, `to_buffer` accepts as a constant generic parameter a buffer size, and returns the buffer filled with the contents of the bytes along with a `Range` that describes the slice of that buffer that contains the bytes. The bytes may not fill the full buffer and the range that case describes where the bytes begins (always 0) and ends. The function is usable regardless of whether the allocator is in use, and is suitable when a reasonable maximum size is known, but an exact size is not.

The `to_alloc_vec` function requires the `alloc` feature as it dynamically allocates the memory required to store the bytes on the guest side.

2024-02-22 18:16 UTC, graydon commented on soroban-sdk/src/bytes.rs
> +    pub fn to_alloc_vec(&self) -> alloc::vec::Vec<u8> {
Unsure. I think `Box<[u8]>` is a bit niche / unknown among rust programmers; but it's a smaller type (2 word fat-pointer vs. 3-word fat-pointer-with-bound), so technically a more minimal thing to return. And you can trivially upgrade it (without reallocating) via `Vec<u8>::from`. Maybe add two methods, `to_alloc_boxed` and `to_alloc_vec` that just calls `to_alloc_boxed().into()`?

2024-02-22 19:35 UTC, graydon requested changes
Generally like it! I expect most people will use BytesBuffer<N> for some fixed-size N and  be perfectly happy with that! Couple small nits inline.

2024-02-22 19:35 UTC, graydon commented on soroban-sdk/src/bytes.rs
> +    range: Range<usize>,
Why a range rather than just a single usize indicating the limit?

2024-02-22 19:35 UTC, graydon commented on soroban-sdk/src/bytes.rs
> +/// stored available.
```suggestion
/// A `BytesBuffer` stores a variable number of bytes, up to a fixed limit `B`, in a fixed-size
/// non-heap-allocated structure. It is a minimal wrapper around a fixed-size `[u8;B]` byte
/// array and a length field indicating the amount of the byte array containing meaningful data.
```

2024-02-22 19:35 UTC, graydon commented on soroban-sdk/src/bytes.rs
> +/// stored available.
Given this type really only exists to cope with awkwardness around heap-allocation and size-variability, I think it'd be helpful to highlight exactly what it means in those terms in its doc-comment.

2024-02-23 05:42 UTC, leighmcculloch commented on soroban-sdk/src/bytes.rs
> +    pub fn to_alloc_vec(&self) -> alloc::vec::Vec<u8> {
Sounds good to me.

It occurred to me it's not particularly simple with stable APIs to make a boxed slice without first making a Vec anyway. So I'll leave it as the vec.

2024-02-23 18:28 UTC, graydon approved these changes
You decided against Box<[u8]>? Either way, LGTM

2024-02-23 18:44 UTC, merged

2024-02-23 22:55 UTC, leighmcculloch commented
> You decided against Box<[u8]>?

The functionality for creating Box for slices is all nightly apis. I couldn't see a way to create one without using unsafe so I bailed. You can create one from a Vec<u8> but that seemed a bit pointless as it would still pull in Vec. 

Lmk if I missed something and there's a safe way to do it.